# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ascend', '0002_auto_20171012_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ascend.professor'),
        ),
    ]
