# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cba', '0003_auto_20171013_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Course',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cba.Course'),
        ),
    ]
