# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(related_name='student', to='Project.Course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Last_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
