# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_course_dep'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.ManyToManyField(related_name='subject', to='Project.Grade'),
        ),
    ]
