# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_subject_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Sex',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('o', 'Female')], default='m', max_length=1),
        ),
    ]
