# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0006_auto_20171004_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='First_name',
            field=models.CharField(help_text='Enter your first name ', max_length=200),
        ),
    ]
