# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0007_auto_20171006_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='Student',
        ),
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.ManyToManyField(related_name='student', to='Project.subject'),
        ),
    ]
