# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0008_auto_20171006_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='Subject',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subject',
        ),
        migrations.AddField(
            model_name='student',
            name='Subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
