# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0009_auto_20171006_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Subject',
        ),
    ]
