# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0011_subject_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='grade',
            new_name='exam',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
        migrations.AddField(
            model_name='subject',
            name='performance',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='quiz',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
    ]
