# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0014_auto_20171006_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_fname', models.CharField(max_length=100)),
                ('prof_mname', models.CharField(max_length=100)),
                ('prof_lname', models.CharField(max_length=100)),
                ('Prof', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prof', to='Project.professor')),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Sex',
            new_name='Gender',
        ),
        migrations.AlterField(
            model_name='subject',
            name='Student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade', to='Project.student'),
        ),
    ]
