# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0015_auto_20171008_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='members',
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
