# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0016_auto_20171008_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('unexcused', 'Unexcused'), ('excused', 'Excused'), ('late', 'Late')], max_length=10, verbose_name='')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.student')),
            ],
        ),
    ]
