# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0016_auto_20171011_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='Students',
        ),
        migrations.AddField(
            model_name='professor',
            name='Students',
            field=models.ManyToManyField(related_name='prof', to='Project.student'),
        ),
    ]
