# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0018_student_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='Subjects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prof_subject', to='Project.subject'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='Students',
            field=models.ManyToManyField(related_name='prof_stud', to='Project.student'),
        ),
    ]
