# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0021_remove_student_professor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='Profs',
            new_name='Professor',
        ),
    ]
