# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0022_auto_20171011_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='Students',
        ),
        migrations.AddField(
            model_name='professor',
            name='Subjects',
            field=models.ManyToManyField(related_name='prof_sub', to='Project.subject'),
        ),
    ]
