# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0023_auto_20171011_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='Subjects',
        ),
    ]
