# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0023_course_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='Student',
            field=models.ManyToManyField(related_name='professor', to='Project.student'),
        ),
    ]
