# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0024_remove_professor_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='MI',
            new_name='Middle_name',
        ),
        migrations.AlterField(
            model_name='student',
            name='Last_name',
            field=models.CharField(help_text='Enter your last name ', max_length=100),
        ),
    ]
