# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-16 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0025_auto_20171012_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='exam',
            new_name='exam_1',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='performance',
            new_name='performance_1',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='quiz',
            new_name='quiz_1',
        ),
    ]
