# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0025_remove_subject_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='Student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.student'),
        ),
    ]
