# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-16 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0026_auto_20171016_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='exam_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='exam_3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='performance_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='performance_3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='quiz_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='quiz_3',
            field=models.IntegerField(null=True),
        ),
    ]
