# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-16 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0027_auto_20171016_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='exam_1',
            field=models.IntegerField(null=True, verbose_name='Trinal Exam'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='exam_2',
            field=models.IntegerField(null=True, verbose_name='Midterm Exam'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='exam_3',
            field=models.IntegerField(null=True, verbose_name='Final Exam'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='performance_1',
            field=models.IntegerField(null=True, verbose_name='Trinal Performance'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='performance_2',
            field=models.IntegerField(null=True, verbose_name='Midterm Performance'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='performance_3',
            field=models.IntegerField(null=True, verbose_name='Final Performance'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='quiz_1',
            field=models.IntegerField(null=True, verbose_name='Trinal Quiz'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='quiz_2',
            field=models.IntegerField(null=True, verbose_name='Midterm Quiz'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='quiz_3',
            field=models.IntegerField(null=True, verbose_name='Final Quiz'),
        ),
    ]
