# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0033_auto_20171010_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='course',
            field=models.ManyToManyField(related_name='professor', to='Project.Course'),
        ),
    ]
