# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0034_professor_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='course',
            field=models.ManyToManyField(related_name='student', to='Project.professor'),
        ),
    ]
