# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0038_remove_subject_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Professor',
            field=models.ManyToManyField(related_name='student', to='Project.professor'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(related_name='Course', to='Project.student'),
        ),
    ]
