# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0039_auto_20171010_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(related_name='student', to='Project.Course'),
        ),
    ]
