# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0041_auto_20171010_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Subject',
            field=models.ManyToManyField(related_name='student', to='Project.subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Professor',
            field=models.ManyToManyField(related_name='student', to='Project.professor'),
        ),
    ]
