# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0042_auto_20171010_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
    ]
