# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0043_remove_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Course',
            field=models.ManyToManyField(related_name='student', to='Project.Course'),
        ),
    ]
