# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0045_auto_20171010_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Subject',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='Professor',
        ),
        migrations.AddField(
            model_name='professor',
            name='Subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='Professor',
            field=models.ManyToManyField(related_name='student', to='Project.professor'),
        ),
    ]
