# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0046_auto_20171010_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.IntegerField(null=True)),
                ('performance', models.IntegerField(null=True)),
                ('exam', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='performance',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='quiz',
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_Discreption',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
