# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0047_auto_20171010_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject_Discreption',
            new_name='subject_Descreption',
        ),
        migrations.AddField(
            model_name='grade',
            name='Subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.subject'),
        ),
    ]
