# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0049_auto_20171010_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Grade',
            field=models.ManyToManyField(related_name='student', to='Project.Grade'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Professor',
            field=models.ManyToManyField(related_name='student', to='Project.professor'),
        ),
    ]
