# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0050_auto_20171010_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='mark',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_Descreption',
            field=models.CharField(max_length=200),
        ),
    ]
