# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0051_auto_20171010_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='Subject',
        ),
        migrations.AddField(
            model_name='subject',
            name='Professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.professor'),
        ),
    ]
