# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 00:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0055_auto_20171011_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Subject',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='Professor',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='grade',
        ),
        migrations.AddField(
            model_name='grade',
            name='Subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.ManyToManyField(related_name='student', to='Project.Grade'),
        ),
    ]
