# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 02:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0064_auto_20171012_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='Professor',
        ),
    ]
