# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0066_auto_20171012_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('bio', models.TextField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='grade',
            name='Student',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='Subject',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='last_name',
        ),
        migrations.AddField(
            model_name='professor',
            name='Teacher',
            field=models.ManyToManyField(related_name='professor', to='Project.Teacher'),
        ),
    ]
