# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0067_auto_20171012_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='Teacher',
        ),
        migrations.AddField(
            model_name='grade',
            name='Student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.student'),
        ),
        migrations.AddField(
            model_name='grade',
            name='Subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.subject'),
        ),
        migrations.AddField(
            model_name='professor',
            name='bio',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='first_name',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='last_name',
            field=models.CharField(default=3, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='Professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.subject'),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
