# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 05:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0068_auto_20171012_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='Student',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='Subject',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='Professor',
        ),
    ]
