# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0072_professor_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='grade',
        ),
    ]
