# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0074_auto_20171012_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='Professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.professor'),
        ),
    ]
