# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0075_auto_20171012_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='Student',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='Subject',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='grade',
        ),
    ]
