# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0077_auto_20171012_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='Mark',
            field=models.CharField(blank=True, choices=[('f', 'Fail'), ('p', 'Pass')], default='Fail', max_length=1),
        ),
    ]
