# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0078_auto_20171012_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='Professor',
        ),
        migrations.AddField(
            model_name='student',
            name='Professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.professor'),
        ),
        migrations.AddField(
            model_name='student',
            name='Subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.subject'),
        ),
    ]
