# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0079_auto_20171012_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='Subject',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Subject',
        ),
    ]
