# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0080_auto_20171013_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='Subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.subject'),
        ),
    ]
