# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0082_auto_20171013_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studen_name', models.CharField(max_length=150, verbose_name='AttendanceRecord')),
            ],
        ),
    ]
